sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  
before_install:
  - docker build -t moylette/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run moylette/react-test npm test -- --coverage

